### ISSUE TITLE
Audio Fix and Hotbar Fix for 1.8.9

### ISSUE THREAD

**Issue by mqtrx** [Sk1erLLC/Patcher#76]
1: In version 1.8.9 (i think 1.12.2 as well) there is a bug with the audio where if any noise is playing in your left or right ear, going in f5 wouldnt flip the audio.

Bug 2: In all versions of Minecraft, the hotbar would sometimes be cutoff by one or 2 pixels for some texture packs, raising the hotbar by 1 or 2 pixels would solve this issue somehow. (if you didnt notice it before now you cant unsee it, sorry lol)

End of message, sincerely, mqtrx

**Comment by SystemlessDev** [comment]
> In version 1.8.9 (i think 1.12.2 as well) there is a bug with the audio where if any noise is playing in your left or right ear, going in f5 wouldnt flip the audio.

This is something we're sadly not very interested in fixing due to it being a very very minor issue that would be very ugly to fix.

> In all versions of Minecraft, the hotbar would sometimes be cutoff by one or 2 pixels for some texture packs, raising the hotbar by 1 or 2 pixels would solve this issue somehow. 

This is sadly something we're not interested in adding either due to the fact that it would most likely cause conflicts with a good portion of existing mods, as well as the code side of things is quite naughty.
